name: Standard CI/CD workflow for Kotlin Docs Flow

on:
  workflow_call:
    inputs:
      aws_region:
        required: false
        type: string
        default: "eu-west-1"
    secrets:
      aws_account_id:
        required: true
      aws_access_key:
        required: true
      aws_secret_key:
        required: true

env:
  # Use secrets and inputs passed in to the workflow
  DEPLOY_TARGET_ACCOUNT: ${{ secrets.aws_account_id }}
  DEPLOY_TARGET_REGION: ${{ inputs.aws_region }}

jobs:
  build:
    name: Build CDK Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"
      - name: Build with Gradle
        run:
          ./gradlew build packageDistribution

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: LambdaArtifacts
          # A pattern that describes what to upload
          path: build/dist/*.zip
          # Behavior if no files are found using the provided path.
          if-no-files-found: error
          # Duration after which artifact will expire in days.
          retention-days: 1

  deploy-app:
    runs-on: ubuntu-latest
    needs: [ build ]
    name: Kotlin Http4k Docs flow app deployment

    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: LambdaArtifacts
          path: build/dist/

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: DEPLOY synthesize & deploy
        run: |
          cd ${GITHUB_WORKSPACE}/infrastructure
          npm install -g aws-cdk
          cdk bootstrap
          cdk deploy -vv --require-approval never --all
